title = "A. Y. Borden"
baseURL = "https://modest-banach-8d0470.netlify.com/"
languageCode = "en-us"
theme = "ananke"
timeout = "600s"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 20

googleAnalytics = ""
enableRobotsTXT = true
