title = "A. Y. Borden"
languageCode = "en-us"
theme = "ananke"
timeout = "600s"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 20

googleAnalytics = ""
enableRobotsTXT = true
