custom_css = ["css/fonts.css", "css/image-hovers.css"]
favicon = "images/new-logo-16.png"
body_classes = "amatic bg-near-white"
post_content_classes = "amatic"
description = ""
# choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
recent_posts_number = 0
