custom_css = ["css/fonts.css", "css/image-hovers.css", "css/global.css"]
favicon = "images/new-logo-16.png"
body_classes = "amatic bg-near-white"
post_content_classes = "amatic"
background_color_class = "bg-black"
recent_posts_number = 0
