title = "A. Y. Borden"
baseURL = "https://modest-banach-8d0470.netlify.com/"
languageCode = "en-us"
theme = "ananke"
timeout = 60000

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 20

googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  custom_css = ["css/fonts.css"]
  favicon = "images/new-logo-16.png"
  body_classes = "indie-flower bg-near-white"
  post_content_classes = "indie-flower"
  description = ""
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 0
