[build]
publish = "public"
command = "HUGO_BASEURL=$URL hugo --debug --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.68.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "HUGO_BASEURL=$DEPLOY_PRIME_URL hugo --gc --minify --buildFuture"

[context.deploy-preview.environment]
HUGO_VERSION = "0.68.3"

[context.branch-deploy]
command = "HUGO_BASEURL=$DEPLOY_PRIME_URL hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.68.3"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
